#!/bin/bash -x

. /etc/default/protege

start()
{
   mkdir --parents /var/log/protege
   chown ${PROTEGE_SANDBOX_USER} /var/log/protege
   SERVER_DIR=${PROTEGE_SERVER_PREFIX}/server
   cd ${SERVER_DIR}

   su ${PROTEGE_SANDBOX_USER} <<-END
     nohup \
       ${JAVA_HOME}/bin/java \
         -Djava.awt.headless=true \
         -server -Djava.rmi.server.hostname=${HOSTNAME} \
         -DentityExpansionLimit=1000000 -Dfile.encoding=UTF-8 \
         -Dorg.protege.owl.server.configuration=metaproject.owl \
         -Djava.util.logging.config.file=logging-unix.properties \
         -classpath lib/felix.jar:lib/ProtegeLauncher.jar \
         org.protege.osgi.framework.Launcher > /dev/null &
END
}

case "$1" in
start)
	start
	;;
esac
